### PR TITLE
Fix broken catch statement causing crashes

### PR DESCRIPTION
**Pull request by fatlard1993**
```
node_modules/globby/index.js:28
	} catch {
	        ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:617:28)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (node_modules/postcss-mixins/index.js:6:14)
```

### CODE REVIEW

**Comment by jaichandra** [comment]
can we fix the checks and do a release please. Our build is broken due to this issue.

**Comment by papb** [comment]
This package only supports Node.js 10 and up:

https://github.com/sindresorhus/globby/blob/master/package.json#L14

Are you using an older version?

**Comment by jaichandra** [comment]
Oh.. thats a problem then.. our jenkins is on node `9.11.2`

**Comment by papb** [comment]
For now, you could use your fork instead of the official release. To do this, you do the following:

* `npm uninstall globby`
* `npm install https://github.com/sindresorhus/globby/tarball/5eb9015c1166065115876ed7f4992f64727d7c1b`

I obtained the URL above by finding your last commit in this PR, https://github.com/sindresorhus/globby/commits/5eb9015c1166065115876ed7f4992f64727d7c1b, and then changing the `/commits/` part of the URL with `/tarball/` - GitHub provides this API feature that `npm` understands perfectly :)

**Pull request closed without merging**
