### PR TITLE
Bump glob to v7.x

### PR DESCRIPTION
**Pull request by shinnn**
includes a bug fix https://github.com/isaacs/node-glob/commit/0ffab1f3cbe2f3c9ec6eab21dc16c8e0d1fe3e0a

### CODE REVIEW

**Comment by UltCombo** [comment]
:+1: 
We should publish a new major version after this is merged, I think.

**Comment by sindresorhus** [comment]
Nothing really useful in that release: https://github.com/isaacs/node-glob/commit/b63c6573059bf7bb1be04670b24f688612efcf71#diff-42ba1d994f4fa8c6ad17a7efae7936ccR3

`glob` seems to be on a major bumping marathon, so I'd rather wait on 8.0.0 (in a couple of weeks? :p). Major versions are expensive for users and this doesn't justify one.

Keeping this open for discovery.

**Comment by shinnn** [comment]
No need to keep this open for discovery, if the next major version will be really released soon.

**Comment by sindresorhus** [comment]
@shinnn That was a joke. I have no insight into when the next version will be released.

I want to keep it open or I'm guaranteed to get many useless PRs bumping the version.

**Comment by shinnn** [comment]
@sindresorhus OK.

**Comment by UltCombo** [comment]
Looks like node-glob's major hasn't changed for a couple months now. I believe we should upgrade and publish a major release.

**Comment by UltCombo** [comment]
Rebased and updated your commit slightly: 678006bb77a6cdb14475d79fca86ba4f588e4094

**Pull request closed without merging**
