### PR TITLE
Work around TypeScript type problem with `URL` global

### PR DESCRIPTION
**Pull request by antongolub**
relates #201

https://github.com/sindresorhus/globby/pull/201#discussion_r785471096

### CODE REVIEW

**Comment by sindresorhus** [comment]
This should not be needed. `URL` is a valid global in Node.js.

**Comment by antongolub** [comment]
Correct, should not be needed. However built-in TS libdefs (4.5.4) does not reflect this fact.

image

 And `@types/node` too.
image

**Comment by antongolub** [comment]
I'll make a PR for TS/definetlyTyped, but right now I'd like to fix our CI/CD.

**Comment by antongolub** [comment]
Clarified for myself what's going on: it seems if we have no explicit `lib` declaration in `compilerOptions`, TS attaches `dom`

image

**Comment by sindresorhus** [comment]
I forgot, this is actually a long running TS issue: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/34960 (I cannot believe they have still not fixed that...)

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/globby/releases/tag/v12.2.0

**Pull request merged**
