### PR TITLE
Accept `URL` in function returned by `isGitIgnored`

### LINKED ISSUE #202: Accept `URL` in function returns by `isGitIgnored()` and `isGitIgnoredSync()`
This is a little different from #176, I didn't implement in  #201

```diff
const isIgnored = await isGitIgnored();

- console.log(isIgnored(fileURLToPath(url)));
+ console.log(isIgnored(url));
```

### PR DESCRIPTION
**Pull request by fisker**
Fixes #202

I just realized this function also accept object with `path`, I guess it's easier to use in `index.js`, but as a public method, I don't think it should do such thing, anyway I didn't touch it.

### CODE REVIEW

**Comment by sindresorhus** [comment]
You need to update the readme too.

**Comment by fisker** [comment]
Ha, you already did..  but  you missed one place.

**Comment by fisker** [comment]
The object with `path` property is also not mentioned there, we should remove support for it.

**Comment by sindresorhus** [comment]
> Ha, you already did.. but you missed one place. isGitIgnored section

Fixed in `main`.

> The object with path property is also not mentioned there, we should remove support for it.

👍

**Pull request merged**
