### PR TITLE
added ignore option for sync

### PR DESCRIPTION
**Pull request by vegetableman**
As discussed on isaacs/node-glob#151

### CODE REVIEW

**Comment by UltCombo** [comment]
Thanks!
I wonder if it would be possible to avoid duplicating so much existing code.
//cc @sindresorhus for reviewing

**Comment by vegetableman** [comment]
Added matcha fix

**Comment by UltCombo** [comment]
LGTM, thanks!
Will do some clean up later.

**Comment by UltCombo** [comment]
https://github.com/sindresorhus/globby/commit/c6ce6a6034d52b7302361932f0e9bd1f5fc9263e

**Comment by sindresorhus** [comment]
Thanks @vegetableman :)

**Pull request merged**
