### PR TITLE
97

### LINKED ISSUE #97: `{extension: false}` and `expandDirectories.extensions` don't work together
[Issuehunt badges](https://issuehunt.io/r/sindresorhus/globby/issues/97)

If using `noext: true` (or `extension: false`, which is the same thing), and `expandDirectories.extensions`, then no results will be returned.

Example:

```js
globby.sync(dirPath, {
  expandDirectories: {
    // Must have more than one extension here.
    extensions: ['md', 'txt'],
  },
  extension: false,
})
```

> There is a $40.00 open bounty on this issue. Add more on [Issuehunt](https://issuehunt.io/r/sindresorhus/globby/issues/97).
> - Checkout the [Issuehunt explorer](https://issuehunt.io/r/sindresorhus/globby/) to discover more funded issues.
> - Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on Issuehunt to raise funds.

### PR DESCRIPTION
**Pull request by janat08**
Fixes #97

### CODE REVIEW

**Comment by janat08** [comment]
Please merge and reward

**Comment by janat08** [comment]
@sindresorhus

**Comment by janat08** [comment]
@sindresorhus

**Comment by sindresorhus** [comment]
It looks like this was fixed in `fast-glob`. Can you update to only include the tests to confirm it's working?

The PR also needs a proper title.

**Comment by sindresorhus** [comment]
Actually, we already have a test for this in `master`.

**Pull request closed without merging**
